# Generated by Django 5.1.2 on 2024-12-05 09:10

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eldertasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Task picture (Max 5MB, recommended 500x500px)",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskmedia",
                        to="eldertasks.task",
                    ),
                ),
            ],
        ),
    ]
