# Generated by Django 5.1.2 on 2024-12-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_backup_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_user_ty_b6cfc8_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
